### ISSUE TITLE
Issues upgrading Mac build to latest CEF Build

### ISSUE THREAD

**Issue by craigzwartble** [acristoffers/CEF3SimpleSample#10]
HI - this is a fantastic example on using CEF, but I am having issues upgrading the Mac build to use the latest CEF. 

To upgrade the CEF Code, i did the following:
     - Downloaded the latest version of CEF 3.2840.1517 and compiled the libcef_dll_wrapper.
     - Copied the libcef_dll_wrapper.a and The Chromium Embeded Framework files into the CEF\MAC Folder  
    - Cleaned and Rebuilt the CEFSimpleSample project

Everything compiles, but when i attempt to run the application, I get the following error

dyld: Library not loaded: @rpath/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Users/john_connah/Library/Developer/Xcode/DerivedData/CEF3SimpleSample-dagfekcnfghhrsfzxuopgebnvifs/Build/Products/Debug/CEF3 Simple Sample.app/Contents/MacOS/CEF3 Simple Sample
  Reason: image not found

If I inspect the package contents, I see that the framework exists in the App Contents.  The run scripts in the xcodeproj perform a install_name_tool 

Has anyone managed to upgrade the CEF Framework and if so, what steps did you take.

Many thanks for any info
CZ

**Comment by acristoffers** [comment]
I just updated the repository (commit 931933d) without any problems. Don't know what happened in your setup. Just git-pull to update to version 3.2704.1434 on macOS. I'll update the Windows and Linux versions later.
