### ISSUE TITLE
Pegar valor de variável ou retorno função no javascript para o C++ síncrono

### ISSUE THREAD

**Issue by rflsouza** [acristoffers/CEF3SimpleSample#12]
Fala Álan, tudo bem?

Eu implementei algumas coisas do CEF, Fiz uma mistura no Client APP com CefBrowserProcessHandler e CefRenderProcessHandler . Para ter os eventos das duas. Mais ou menos assim:
```
class ClientApp : public CefApp,
                  public CefBrowserProcessHandler,
				  public CefRenderProcessHandler 
```

Eu consegui fazer as integrações de Javascript, mas tenho algumas dúvidas, queria ver se você pode me ajudar.

1) Queria saber se você tem algum exemplo para executar uma função no C++ e pegar o retorno da função de forma síncrono.  Antes de fechar eu queria confirmar se está tudo finalizado na minha página.

2) Tentei de diversas forma entrar no Contexto _"frame->GetV8Context(), CefV8Context::GetEnteredContext() e CefV8Context::GetCurrentContext()"_ fora das funções OnWebKitInitialized, OnContextCreated e não consigo.  Tentou isso alguma vez?

3) Uma vez que fez o Binding "OnContextCreated " eu consigo pegar o valor quando é atualizado na página? Essa eu vou fazer uns testes também, se mudar no Javascript se ela reflete ou se foi feito apenas para criar na página.

Abraços,
Rafael

**Comment by acristoffers** [comment]
Olá @rflsouza,

1. Não é possível com o CEF3. Ele usa o modelo atual do Chromium onde o seu código C++ roda em um processo e o navegador em outro. Toda comunicação é feita usando IPC de forma assíncrona.

2. No meu exemplo eu uso de fora, em ClientV8ExtensionHandler::Execute.

3. Não entendi.

**Comment by rflsouza** [comment]
1. Na [documentação](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-synchronous-requests) eles até comenta que da para fazer usando  synchronous XMLHttpRequests. Porém não vi nenhum exemplo. Entendo que não é a melhor forma, além de fazer bloqueios também.

2. Nas funções das implementações CefRenderProcessHandler vai tranquilo, consegui fazer a chamada também, pois tem o contexto, o problema é fora das funções, exemplo: eu tenho uma variável criado na View do MFC com o browser, ali eu consigo pegar o frame, mas não consigo pegar o contexto. Mas como tenho o frame eu também consigo rodar um JavaScript.  

3. Consegui fazer o exemplo usando o **Objects with Accessors**.  Qualquer alteração na variável que foi criada no html eu consigo ter o valor no C++. Muito legal.  

4. Agora não entendi direto como implementar o [JS Callbacks](https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration.md#markdown-header-using-js-callbacks).  Esse eu tenho que ver direito, pois acho que seria legal de usar também.


Você utiliza o CEF em algum projeto ou apenas testes?

Obrigado pelo retorno.

**Comment by acristoffers** [comment]
Só utilizei para um projeto, que foi quando decidir fazer estes repositórios. Na época achei que o exemplo básico do projeto era poluído d+ para ser entendido por quem nunca usou o CEF. Depois não tive mais necessidade. Para projetos onde o CEF seria aplicado estou usando Electron. E só usei o CEF porque a QtWebKit é meio desatualizada, não oferecia suporte a uma funcionalidade que eu precisava (quebra de página por CSS na impressão). Se fosse pra fazer hoje preferiria o Electron mesmo.

**Comment by rflsouza** [comment]
Entendi, dei uma olhada nesse Electron e é bem interessante também...  Obrigado pelas respostas.

abraços.
