### ISSUE TITLE
[suggestion] Support CMake

### ISSUE THREAD

**Issue by prsolucoes** [acristoffers/CEF3SimpleSample#16]
Hi,

A suggestion that i want do is support cmake into your example.

CMake generate project for xcode/visual-studio/ninja/makefile/etc.

Thanks.

**Comment by acristoffers** [comment]
CMake can be added. I don't think they used it when I created the project. Their official example uses it now, but the scrips are complicated, probably because they build it and libs in the same project. I'll see what I can do in a project-specific fashion.

**Comment by acristoffers** [comment]
Added.
