### ISSUE TITLE
Missing header files in source?

### ISSUE THREAD

**Issue by StarPlayrX** [acristoffers/CEF3SimpleSample#25]
missing

#include "include/cef_devtools_message_observer.h"
#include "include/cef_registration.h"
#include "include/cef_registration.h"
#include "include/cef_media_router.h"
... 

can't continue with the missing header files.

**Comment by acristoffers** [comment]
Should be fixed in the latest commit.

**Comment by StarPlayrX** [comment]
I got it to compile.

quick question, how do I add compline arguments for CEF? I was able to add a couple to CEF.Swift from another author but I can’t seem to figure out where in yours I can add that in Objective-C?

thanks for your assistance,

Todd

ps

I like your because it has a native Mac window which for some reason o can’t get to work in CEF.Swift

**Comment by acristoffers** [comment]
Compline arguments? Compiler arguments? Those are managed by Xcode, you have to adjust it in the project settings, and how to do it depends on what you want to do.
