### ISSUE TITLE
the app too big

### ISSUE THREAD

**Issue by a1726015841** [acristoffers/CEF3SimpleSample#30]
the app build have 1.63GB size

**Comment by acristoffers** [comment]
Thanks for the bug report.
As you don't say what platform or tool you are using, I'm assuming it is macOS. The reasong the bundle is so big is because it copies the CEF framework 5 times. I changed the CMake script so it removes 4 of the copies and points the executables to the remaining copy, bringing the size down to about 200MB. I don't know how to instruct Xcode to do it automatically, but either adding a post-build script or doing it manually aftewards should work.
The changed CMakeLists.txt is already published, just update your local copy and run make again.
If it is another platform, tell me which, and also which tool you're using to build.

**Comment by a1726015841** [comment]
Thank you for answering my questions during your busy schedule! I used Xcode to build the macos environment, and then used your latest CMakeList.txt script, recompiled under the new folder build, and found a new error, Error copying directory from "/Volumes/data/ TestSimple/CEF3SimpleSample-master/build/CEF3SimpleSample Helper.app" to "/Volumes/data/TestSimple/CEF3SimpleSample-master/build/CEF3SimpleSample.app/Contents/Frameworks/CEF3SimpleSample Helper.app".
Command PhaseScriptExecution failed with a nonzero exit code
How should I deal with it?

**Comment by acristoffers** [comment]
Hi. That's a weird error to have, maybe something went wrong before that? Can you verify that the helper app exists? And what is the filesystem of this mount?

--
Álan Crístoffer

**Comment by a1726015841** [comment]
/Volumes/data/ TestSimple/CEF3SimpleSample-master/build/CEF3SimpleSample Helper.app. This file exists after recompiling cmakelist.txt. Xcode prompts this error

**Comment by a1726015841** [comment]
Can you tell me how to manually remove the cef framework included in xcode 4 times?

**Comment by acristoffers** [comment]
Inside CEF3SimpleSample.app (right-click and select Show Package Contents) there is a folder Contents/Frameworks with 4 helper apps. You have to open them and remove their Contents/Frameworks folder. After that you have to run

```install_name_tool -change "@executable_path/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework" "@executable_path/../../../Chromium Embedded Framework.framework/Chromium Embedded Framework" EXEC_PATH```

for each of the helper app's executable (inside Contents/MacOS - replace EXEC_PATH with the actual executable path)

**Comment by a1726015841** [comment]
Ok. Thank you very much! I will use your method to study this one. Thank you

**Comment by acristoffers** [comment]
I just pushed an update to the Xcode project that should correctly pack by default. It runs those commands for you and does not embed the extra copies.
The copy not working error, however, is kinda linked to your setup. I believe your data drive is not APFS nor HPFS+, and that may be what is causing problems. Try creating the build folder in an APFS driver to see if that is it. Hope it is, as I have no idea what else might be going on there.

**Comment by a1726015841** [comment]
thank you very much! Let me try

**Comment by a1726015841** [comment]
Already, thank you very much!
