### ISSUE TITLE
abcout dispatch_get_main_queue

### ISSUE THREAD

**Issue by orientwhite** [acristoffers/CEF3SimpleSample#34]
Following the last question, my message has been sent to the main process. But it is not executed in the main process using'dispath_async(dispatch_get_main_queue())' closure

**Comment by acristoffers** [comment]
Sorry but this is not the place for this. This project sole purpose is to show the bare minimum to get CEF3 running with javascript<->C++ interop. Now you are getting into Apple's internals. I recommend you search/ask in places like StackOverflow.
