### ISSUE TITLE
How to add CefDragHandler?

### ISSUE THREAD

**Issue by hussainkadori** [acristoffers/CEF3SimpleSample#35]
Hi,
How to add DragHandler for the ClientHandler to work with `-webkit-app-region: drag`

I added the DragHandler to the ClientHandler, How to send message to the main loop?

```
void ClientHandler::OnDraggableRegionsChanged(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame,
                                              const std::vector<CefDraggableRegion> &regions) {
    CEF_REQUIRE_UI_THREAD();

}
```

**Comment by acristoffers** [comment]
I'm sorry, I've stopped using CEF a long time ago. I only keep this repo because it's still a simpler way of understanding the minimum required setup for a CEF project than the cefclient example.
