### ISSUE TITLE
Do you want to Support Qt?

### ISSUE THREAD

**Issue by toby20130333** [acristoffers/CEF3SimpleSample#9]
Hi @acristoffers do you want to support to qt?
Qt Webkit is bad for real application,so please.

**Comment by acristoffers** [comment]
QtWebKit was superseeded by QtWebEngine. You should use that instead. If you want to join CEF and Qt yourself, just look on how to join both event loops. You probably need to call CEF's event processing routine from Qt's event loop.

**Comment by toby20130333** [comment]
@acristoffers 
thanks
but webengine donn't support mingw.
